language: node_js

node_js:
- node
- 'lts/*'
before_install:
  - npm install -g codecov
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha -- --compilers js:babel-register --recursive
  - codecov
after_success:
  - codecov --file coverage/lcov.info --disable search
